---
title: "analysis"
output: html_document
date: '2022-08-31'
---

```{r}
library(tidyverse)
r = readLines("/data/home/wangzz/github/splicing-universal-experiment/total_experiment/experiment/logistic.out")
r = r[str_starts(r,'\\{')]
```


```{r}
df = r %>% 
  str_extract_all("(-?[0-9]\\d*\\.?\\d*e?-?\\d*)|nan") %>% 
  sapply(as.matrix) %>% 
  t() %>% 
  as_tibble()
```


```{r}
colnames(df) = c('n', 'seed', 'Lasso_accuracy', 'Lasso_best_lambda', 'Lasso_time', 'GraHTP_accuracy', 'GraHTP_time', 'GraHTP_cv_accuracy', 'GraHTP_best_step_size', 'GraHTP_cv_time', 'GraSP_accuracy', 'GraSP_time', 'SCOPE_accuracy', 'SCOPE_time')
df = df %>% 
  mutate(across(everything(), as.numeric)) 
```

## count

```{r}
df = df %>%
  filter(!is.na(Lasso_accuracy))
```


```{r}
df %>% 
  group_by(n) %>% count()
```





```{r}
df2 = bind_rows(
  df %>% 
    select(n,time=SCOPE_time,accuracy=SCOPE_accuracy) %>% 
    mutate(method = 'SCOPE'),
  df %>% 
    select(n,time=GraHTP_time,accuracy=GraHTP_accuracy) %>% 
    mutate(method = 'GraHTP'),
  df %>% 
    select(n,time=GraHTP_cv_time,accuracy=GraHTP_cv_accuracy) %>% 
    mutate(method = 'GraHTP_cv'),
  df %>% 
    select(n,time=GraSP_time,accuracy=GraSP_accuracy) %>% 
    mutate(method = 'GraSP'),
  df %>% 
    select(n,time=Lasso_time,accuracy=Lasso_accuracy) %>% 
    mutate(method = 'Lasso')
)
```


```{r}
df %>% ggplot() +
  geom_point(aes(n,GraHTP_best_step_size),color="red") 
df %>% ggplot() +
  geom_point(aes(n,Lasso_best_lambda),color="blue")
```

## plot


```{r}
df2 %>% 
  group_by(n,method) %>% 
  summarise(accuracy = mean(accuracy)) %>% 
  ggplot(aes(n, accuracy, color = method)) +
    labs(x='Sample size', y='Accuracy') +
    geom_point() +
    geom_line() + 
    ylim(0,1)
```

```{r}
df2 %>% 
  group_by(n,method) %>% 
  summarise(time = mean(time)) %>% 
  #filter(method == "GraSP") %>% 
  #filter(!method%in%c("GraHTP_cv")) %>% 
  ggplot(aes(n, time, color = method)) +
    labs(x='Sample size', y='Runtime (Sec)') +
    geom_line() +
    scale_y_log10() +
    geom_point() 
  
```
