---
title: "analysis"
output: html_document
date: '2022-08-31'
---

```{r}
library(tidyverse)
df = read_csv('/data/home/wangzz/github/splicing-universal-experiment/hyper_parameter/init_strategy.csv') %>% 
  select(-...1)
```

```{r}
df2 = bind_rows(
  df %>% 
    select(n, model,time=margin_time,accuracy=margin_accuracy) %>% 
    mutate(method = 'Margin'),
  df %>% 
    select(n, model,time=sacrifice_time,accuracy=sacrifice_accuracy) %>% 
    mutate(method = 'Sacrifice'),
  df %>% 
    select(n, model,time=random_time,accuracy=random_accuracy) %>% 
    mutate(method = 'Random')
) 
```

```{r}

df2 = df2 %>% 
  filter(!is.na(time))

df2$model = factor(df2$model, levels = c("Linear", "Classification", "Ising"))

df2 %>% 
  group_by(n, model, method) %>% 
  count()
```



```{r}
df_n = df2 %>% 
  filter(method!="Margin") %>% 
  group_by(n,model,method) %>% 
  summarise(accuracy = mean(accuracy), time = mean(time))
```

## plot

```{r}
p1 = 
ggplot(df_n, aes(n, accuracy, color = method, shape = method)) +
    labs(x='n', y='Accuracy') +
    geom_line() +
    geom_point() +
    #ylim(0,1) +
    labs(color='Initialization strategy', shape = "Initialization strategy")  +
    facet_grid(model ~ ., scale = "free")
```

```{r}
p2 = 
ggplot(df_n, aes(n, time, color = method, shape = method)) +
    labs(x='n', y='Runtime (Sec)') +
    geom_line() +
    geom_point() +
    labs(color='Initialization strategy', shape = "Initialization strategy")  +
    facet_grid(model ~ ., scale = "free")
```

```{r}
library(ggpubr)

page = ggarrange(p1,p2,nrow=1,ncol=2,legend = 'bottom', common.legend = TRUE)

ggexport(page, filename = 'init.pdf', width = 10)
```

