---
title: "omp"
output: html_document
date: '2022-08-04'
---

```{r}
library(tidyverse)
info = read_csv('data/info.csv')
data = read_csv('data/data.csv')
```
```{r}
library(Rfast)

omp_logistic <- function (y, x, support_size) 
{
  tic <- proc.time()
  dm <- dim(x)
  d <- dm[2]
  n <- dm[1]
  ind <- 1:d
  x <- Rfast::standardise(x)
  oop <- options(warn = -1)
  on.exit(options(oop))

  p <- sum(y)/n
  ela <- Rfast::eachcol.apply(x, y)
  sel <- which.max(abs(ela))
  sela <- sel
  names(sela) <- NULL
  mod <- Rfast::glm_logistic(x[, sel], y)
  est <- exp(-mod$be[1] - x[, sel] * mod$be[2])
  res <- y - 1/(1 + est)
  ind[sel] <- 0
  i <- 2
  for(index in seq_len(support_size-1)) {
    r <- numeric(d)
    i <- i + 1
    r[ind] <- Rfast::eachcol.apply(x, res, indices = ind[ind > 
      0], oper = "*", apply = "sum")
    sel <- which.max(abs(r))
    sela <- c(sela, sel)
    mod <- Rfast::glm_logistic(x[, sela], y)
    est <- as.vector(exp(-mod$be[1] - x[, sela] %*% 
      mod$be[-1]))
    res <- y - 1/(1 + est)
    ind[sela] <- 0
  }

  list(runtime = proc.time() - tic, info = sela)
}

```

```{r}
support.size = 20
n = c()
time = c()
accuracy = c()
for(idx in info$id){
  x = data %>% 
  filter(id==idx) %>% 
  select(starts_with('X')) %>% 
  as.matrix()

  y = data %>% 
    filter(id==idx) %>% 
    select(y) %>% 
    as.matrix() %>% 
    as.vector()
  
  coef = info %>% 
    filter(id==idx) %>% 
    select(starts_with('B')) %>% 
    as.matrix() %>% 
    as.vector()
  
  r = omp_logistic(y,x,support_size = support.size)
  
  n = c(n, length(y))
  accuracy = c(accuracy, length(intersect(r$info, which(coef!=0))) / support.size)
  time = c(time, r[["runtime"]][["elapsed"]])
}
```

```{r}
tibble(method = 'omp',n=n,time=time,accuracy=accuracy) %>% 
  write_csv('results/omp_2.csv')
```


## use data from R

```{r}
library(abess)
test_omp <- function(n,p,support.size,rho,snr,seed){
  dataset <- generate.data(n, p, support.size,
    family = "binomial", seed = seed, cortype = 2, rho = rho, snr = snr
  )

  r = omp_logistic(dataset[["y"]],dataset[["x"]],support_size = support.size)
  
  list(
    n = length(dataset[["y"]]),
    accuracy = length(intersect(r$info, which(dataset$beta!=0))) / support.size,
    time = r[["runtime"]][["elapsed"]]
  )
}
```
```{r}
n_list = seq.int(500,11000,700)
seed = 12

ns = c()
time = c()
accuracy = c()
for(n in n_list){
  r = test_omp(n,p=1000,support.size=10,rho=0.7,snr=0.05,seed=seed)
  seed = seed + 1
  ns = c(ns, r$n)
  accuracy = c(accuracy, r$accuracy)
  time = c(time, r$time)
}
```


```{r}
High.noise.High.correlation = tibble(n=ns,time=time,accuracy=accuracy) 
```

```{r}
High.noise.High.correlation
```

```{r}
tibble(n=ns,time=time,accuracy=accuracy) %>%
  ggplot(aes(n,accuracy)) +
    geom_point()
```

